<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <div class="form-group">
        <label for="name">Name</label>
        <?php echo $this->tag->textField(["name","class" => "form-control","placeholder" => "Enter full name"]); ?>
    </div>

    <div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $this->tag->emailField(["email","class" => "form-control","placeholder" => "Enter email address"]); ?>
</div>

    <div class="form-group">
        <?php echo $this->tag->submitButton(["Register","class" => "form-control"]); ?>
    </div>

</form>